const data = [
  {
    pid: 63969,
    name: "wibu-server",
    pm2_env: {
      kill_retry_time: 100,
      windowsHide: true,
      username: "bip",
      treekill: true,
      automation: true,
      pmx: true,
      instance_var: "NODE_APP_INSTANCE",
      watch: false,
      autorestart: true,
      autostart: true,
      vizion: true,
      merge_logs: true,
      env: {
        PORT: "3007",
        NEXT_PUBLIC_WIBU_URL: "localhost:3007",
        NVM_INC: "/Users/bip/.nvm/versions/node/v20.14.0/include/node",
        TERM_PROGRAM: "vscode",
        rvm_bin_path: "/Users/bip/.rvm/bin",
        ANDROID_HOME: "/Users/bip/Library/Android/sdk",
        PYENV_ROOT: "/Users/bip/.pyenv",
        GEM_HOME: "/Users/bip/.rvm/gems/ruby-3.2.2",
        NVM_CD_FLAGS: "",
        SHELL: "/bin/bash",
        TERM: "xterm-256color",
        TMPDIR: "/var/folders/1_/vncl95fd4h59vq771z5plcv40000gn/T/",
        IRBRC: "/Users/bip/.rvm/rubies/ruby-3.2.2/.irbrc",
        HOMEBREW_REPOSITORY: "/opt/homebrew",
        CONDA_SHLVL: "1",
        TERM_PROGRAM_VERSION: "1.94.0",
        CONDA_PROMPT_MODIFIER: "(base) ",
        ORIGINAL_XDG_CURRENT_DESKTOP: "undefined",
        MallocNanoZone: "0",
        TERM_SESSION_ID: "319B31B8-8C0F-4A76-85FE-8F0310D220B1",
        MY_RUBY_HOME: "/Users/bip/.rvm/rubies/ruby-3.2.2",
        NVM_DIR: "/Users/bip/.nvm",
        USER: "bip",
        COMMAND_MODE: "unix2003",
        CONDA_EXE: "/opt/homebrew/Caskroom/miniforge/base/bin/conda",
        rvm_path: "/Users/bip/.rvm",
        SSH_AUTH_SOCK: "/private/tmp/com.apple.launchd.lPMFEeVpdj/Listeners",
        __CF_USER_TEXT_ENCODING: "0x1F5:0x0:0x0",
        _CE_CONDA: "",
        rvm_prefix: "/Users/bip",
        PATH: "/Users/bip/.codeium/windsurf/bin:/opt/homebrew/opt/qt@5/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/bison/bin:/Users/bip/.rvm/gems/ruby-3.2.2/bin:/Users/bip/.rvm/gems/ruby-3.2.2@global/bin:/Users/bip/.rvm/rubies/ruby-3.2.2/bin:/Users/bip/.nvm/versions/node/v20.14.0/bin:/Users/bip/.pyenv/shims:/Users/bip/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/bip/.codeium/windsurf/bin:/Users/bip/.cargo/bin:/opt/homebrew/Caskroom/miniforge/base/bin:/opt/homebrew/Caskroom/miniforge/base/condabin:/opt/homebrew/opt/qt@5/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/bison/bin:/Users/bip/.rvm/gems/ruby-3.2.2/bin:/Users/bip/.rvm/gems/ruby-3.2.2@global/bin:/Users/bip/.rvm/rubies/ruby-3.2.2/bin:/Users/bip/.nvm/versions/node/v20.14.0/bin:/Users/bip/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/bip/development/flutter/bin:/Users/bip/.rvm/bin:/Users/bip/Library/Android/sdk/platform-tools:/Users/bip/Library/Android/sdk/tools:/Users/bip/development/flutter/bin:/Users/bip/Library/Android/sdk/platform-tools:/Users/bip/Library/Android/sdk/tools",
        XML_CATALOG_FILES:
          "file:///opt/homebrew/Caskroom/miniforge/base/etc/xml/catalog file:///etc/xml/catalog",
        LaunchInstanceID: "3014187B-5B0A-4257-9A3D-8FB45DE905B8",
        CONDA_PREFIX: "/opt/homebrew/Caskroom/miniforge/base",
        __CFBundleIdentifier: "com.exafunction.windsurf",
        PWD: "/Users/bip/Documents/projects/wibu/wibu-server",
        EDITOR: "nano",
        LANG: "en_US.UTF-8",
        VSCODE_GIT_ASKPASS_EXTRA_ARGS: "",
        XPC_FLAGS: "0x0",
        XPC_SERVICE_NAME: "0",
        _CE_M: "",
        rvm_version: "1.29.12 (latest)",
        HOME: "/Users/bip",
        SHLVL: "3",
        PYENV_SHELL: "bash",
        VSCODE_GIT_ASKPASS_MAIN:
          "/Applications/Windsurf.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
        HOMEBREW_PREFIX: "/opt/homebrew",
        LOGNAME: "bip",
        CONDA_PYTHON_EXE: "/opt/homebrew/Caskroom/miniforge/base/bin/python",
        VSCODE_GIT_IPC_HANDLE:
          "/var/folders/1_/vncl95fd4h59vq771z5plcv40000gn/T/vscode-git-c55afefad6.sock",
        LC_CTYPE: "UTF-8",
        GEM_PATH:
          "/Users/bip/.rvm/gems/ruby-3.2.2:/Users/bip/.rvm/gems/ruby-3.2.2@global",
        NVM_BIN: "/Users/bip/.nvm/versions/node/v20.14.0/bin",
        CONDA_DEFAULT_ENV: "base",
        VSCODE_GIT_ASKPASS_NODE:
          "/Applications/Windsurf.app/Contents/Frameworks/Windsurf Helper (Plugin).app/Contents/MacOS/Windsurf Helper (Plugin)",
        GIT_ASKPASS:
          "/Applications/Windsurf.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
        HOMEBREW_CELLAR: "/opt/homebrew/Cellar",
        INFOPATH: "/opt/homebrew/share/info:/opt/homebrew/share/info:",
        Q_NEW_SESSION: "1",
        RUBY_VERSION: "ruby-3.2.2",
        SECURITYSESSIONID: "186a5",
        COLORTERM: "truecolor",
        _: "/Users/bip/.nvm/versions/node/v20.14.0/bin/pm2",
        PM2_USAGE: "CLI",
        PM2_HOME: "/Users/bip/.pm2",
        "wibu-server": {},
        unique_id: "ce0e33a0-d61b-4c02-86af-c69424201431",
      },
      args: ["-c", "bun run .next/standalone/server.js"],
      namespace: "wibu-server",
      filter_env: [],
      name: "wibu-server",
      node_args: [],
      pm_exec_path: "/bin/bash",
      pm_cwd: "/Users/bip/Documents/projects/wibu/wibu-server",
      exec_interpreter: "none",
      exec_mode: "fork_mode",
      instances: 1,
      pm_out_log_path: "/Users/bip/.pm2/logs/wibu-server-out.log",
      pm_err_log_path: "/Users/bip/.pm2/logs/wibu-server-error.log",
      pm_pid_path: "/Users/bip/.pm2/pids/wibu-server-0.pid",
      km_link: false,
      vizion_running: false,
      NODE_APP_INSTANCE: 0,
      PORT: "3007",
      NEXT_PUBLIC_WIBU_URL: "localhost:3007",
      NVM_INC: "/Users/bip/.nvm/versions/node/v20.14.0/include/node",
      TERM_PROGRAM: "vscode",
      rvm_bin_path: "/Users/bip/.rvm/bin",
      ANDROID_HOME: "/Users/bip/Library/Android/sdk",
      PYENV_ROOT: "/Users/bip/.pyenv",
      GEM_HOME: "/Users/bip/.rvm/gems/ruby-3.2.2",
      NVM_CD_FLAGS: "",
      SHELL: "/bin/bash",
      TERM: "xterm-256color",
      TMPDIR: "/var/folders/1_/vncl95fd4h59vq771z5plcv40000gn/T/",
      IRBRC: "/Users/bip/.rvm/rubies/ruby-3.2.2/.irbrc",
      HOMEBREW_REPOSITORY: "/opt/homebrew",
      CONDA_SHLVL: "1",
      TERM_PROGRAM_VERSION: "1.94.0",
      CONDA_PROMPT_MODIFIER: "(base) ",
      ORIGINAL_XDG_CURRENT_DESKTOP: "undefined",
      MallocNanoZone: "0",
      TERM_SESSION_ID: "319B31B8-8C0F-4A76-85FE-8F0310D220B1",
      MY_RUBY_HOME: "/Users/bip/.rvm/rubies/ruby-3.2.2",
      NVM_DIR: "/Users/bip/.nvm",
      USER: "bip",
      COMMAND_MODE: "unix2003",
      CONDA_EXE: "/opt/homebrew/Caskroom/miniforge/base/bin/conda",
      rvm_path: "/Users/bip/.rvm",
      SSH_AUTH_SOCK: "/private/tmp/com.apple.launchd.lPMFEeVpdj/Listeners",
      __CF_USER_TEXT_ENCODING: "0x1F5:0x0:0x0",
      _CE_CONDA: "",
      rvm_prefix: "/Users/bip",
      PATH: "/Users/bip/.codeium/windsurf/bin:/opt/homebrew/opt/qt@5/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/bison/bin:/Users/bip/.rvm/gems/ruby-3.2.2/bin:/Users/bip/.rvm/gems/ruby-3.2.2@global/bin:/Users/bip/.rvm/rubies/ruby-3.2.2/bin:/Users/bip/.nvm/versions/node/v20.14.0/bin:/Users/bip/.pyenv/shims:/Users/bip/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/bip/.codeium/windsurf/bin:/Users/bip/.cargo/bin:/opt/homebrew/Caskroom/miniforge/base/bin:/opt/homebrew/Caskroom/miniforge/base/condabin:/opt/homebrew/opt/qt@5/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/bison/bin:/Users/bip/.rvm/gems/ruby-3.2.2/bin:/Users/bip/.rvm/gems/ruby-3.2.2@global/bin:/Users/bip/.rvm/rubies/ruby-3.2.2/bin:/Users/bip/.nvm/versions/node/v20.14.0/bin:/Users/bip/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/bip/development/flutter/bin:/Users/bip/.rvm/bin:/Users/bip/Library/Android/sdk/platform-tools:/Users/bip/Library/Android/sdk/tools:/Users/bip/development/flutter/bin:/Users/bip/Library/Android/sdk/platform-tools:/Users/bip/Library/Android/sdk/tools",
      XML_CATALOG_FILES:
        "file:///opt/homebrew/Caskroom/miniforge/base/etc/xml/catalog file:///etc/xml/catalog",
      LaunchInstanceID: "3014187B-5B0A-4257-9A3D-8FB45DE905B8",
      CONDA_PREFIX: "/opt/homebrew/Caskroom/miniforge/base",
      __CFBundleIdentifier: "com.exafunction.windsurf",
      PWD: "/Users/bip/Documents/projects/wibu/wibu-server",
      EDITOR: "nano",
      LANG: "en_US.UTF-8",
      VSCODE_GIT_ASKPASS_EXTRA_ARGS: "",
      XPC_FLAGS: "0x0",
      XPC_SERVICE_NAME: "0",
      _CE_M: "",
      rvm_version: "1.29.12 (latest)",
      HOME: "/Users/bip",
      SHLVL: "3",
      PYENV_SHELL: "bash",
      VSCODE_GIT_ASKPASS_MAIN:
        "/Applications/Windsurf.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
      HOMEBREW_PREFIX: "/opt/homebrew",
      LOGNAME: "bip",
      CONDA_PYTHON_EXE: "/opt/homebrew/Caskroom/miniforge/base/bin/python",
      VSCODE_GIT_IPC_HANDLE:
        "/var/folders/1_/vncl95fd4h59vq771z5plcv40000gn/T/vscode-git-c55afefad6.sock",
      LC_CTYPE: "UTF-8",
      GEM_PATH:
        "/Users/bip/.rvm/gems/ruby-3.2.2:/Users/bip/.rvm/gems/ruby-3.2.2@global",
      NVM_BIN: "/Users/bip/.nvm/versions/node/v20.14.0/bin",
      CONDA_DEFAULT_ENV: "base",
      VSCODE_GIT_ASKPASS_NODE:
        "/Applications/Windsurf.app/Contents/Frameworks/Windsurf Helper (Plugin).app/Contents/MacOS/Windsurf Helper (Plugin)",
      GIT_ASKPASS:
        "/Applications/Windsurf.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
      HOMEBREW_CELLAR: "/opt/homebrew/Cellar",
      INFOPATH: "/opt/homebrew/share/info:/opt/homebrew/share/info:",
      Q_NEW_SESSION: "1",
      RUBY_VERSION: "ruby-3.2.2",
      SECURITYSESSIONID: "186a5",
      COLORTERM: "truecolor",
      _: "/Users/bip/.nvm/versions/node/v20.14.0/bin/pm2",
      PM2_USAGE: "CLI",
      PM2_HOME: "/Users/bip/.pm2",
      unique_id: "ce0e33a0-d61b-4c02-86af-c69424201431",
      status: "online",
      pm_uptime: 1744613425154,
      axm_actions: [],
      axm_monitor: {},
      axm_options: {},
      axm_dynamic: {},
      created_at: 1744613425154,
      pm_id: 0,
      restart_time: 0,
      unstable_restarts: 0,
      version: "N/A",
      versioning: null,
    },
    pm_id: 0,
    monit: { memory: 4866048, cpu: 0 },
  },
];

declare module "@/types/process" {
  export type PROCESS = (typeof data)[0];
}
