name: connect ssh
description: "Connect to VPS"
inputs:
  env:
    description: "Environment"
    required: true
runs:
  using: "shell"
  steps:
    - name: Connect to VPS
      run: |
        chmod +x $GITHUB_ACTION_PATH/entrypoint.sh
        $GITHUB_ACTION_PATH/entrypoint.sh ${{ inputs.command }}