name: screenshot
on:
  workflow_dispatch:
    inputs:
      data:
        description: "data"
        required: true
        default: "null"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: run bun install workspace
        run: bun install

      # Ambil screenshot menggunakan Puppeteer
      - name: Take screenshot
        run: |
          bun run screenshot.ts

      # Upload screenshot sebagai artifact
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png
