name: screenshot
on:
  workflow_dispatch:
    inputs:
      data:
        description: "data"
        required: true
        default: "null"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: run bun install workspace
        run: bun install

      # Ambil screenshot menggunakan Puppeteer
      - name: Take screenshot
        run: |
          echo "Installing playwright..."
          bunx playwright install  
          E=$(cat <<EOF
          import { chromium } from 'playwright';
          import fs from 'fs';

          (async () => {
            try {
                console.log("Launching browser...");
                const browser = await chromium.launch();
                const page = await browser.newPage();

                // Navigasi ke URL target
                console.log("Navigating to URL...");
                await page.goto('https://darmasaba.muku.id', { waitUntil: 'networkidle' });

                // Mengambil screenshot sebagai buffer
                console.log("Taking screenshot...");
                const screenshotBuffer = await page.screenshot({ fullPage: true });

                // Konversi buffer ke string base64
                const screenshotBase64 = screenshotBuffer.toString('base64');

                // Simpan string base64 ke file `screenshot.txt`
                console.log("Saving screenshot as base64 to screenshot.txt...");
                fs.writeFileSync('screenshot.txt', screenshotBase64);

                console.log("Screenshot saved as base64 in screenshot.txt");

                // Tutup browser
                console.log("Closing browser...");
                await browser.close();
            } catch (error) {
                console.error("Error occurred:", error);
            }
          })();
          EOF
          )

          bun -e "$E"
          ls

      # Upload screenshot sebagai artifact
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png
